# This is a basic workflow to help you get started with Actions

name: QuickRemove

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  RemoveDir:
    name: Remove Directory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        
      - name: Config Git
        run: git config --global user.name "Github Actions"
        shell: bash
        
      - name: Remove File
        run: git rm -r ./.vs/ ; git rm -r ./.github/workflows/
        shell: bash
        
      - name: Commit and push
        run: git commit -m "Deleted the file from the git repository" ; git push
        shell: bash
  
